# Generated by Django 6.0.6 on 2026-07-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0002_rename_tittle_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_items', to='product.product'),
        ),
    ]
